name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        # Run on the latest minor release of Go 1.18:
        go-version: ^1.18
      id: go

    - uses: actions/checkout@v2

    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: install build dependencies
      run: sudo apt update && sudo apt install libgtk-3-dev libcairo2-dev libglib2.0-dev

    - name: run tests
      run: go test -v ./...

    - name: install binaries
      run: go install ./cmd/...
